#!/bin/sh

echo 'Type create user FOO with superuser (or use more restricted permissions)';
sudo -u postres psql;
echo 'Creating XTaTIK database';
createdb XTaTIK;
echo 'Connecting to XTaTIK database. Setup the tables';
psql XTaTIK;